Reorder svelte_frontend gh actions workflow

diff --git a/.github/workflows/svelte_frontends.yml b/.github/workflows/svelte_frontends.yml
--- a/.github/workflows/svelte_frontends.yml
+++ b/.github/workflows/svelte_frontends.yml
@@ -27,6 +27,10 @@ jobs:
         working-directory: svelte_frontends
         run: npm ci
 
+      - name: Build
+        working-directory: svelte_frontends
+        run: npm run build || echo "❌ Build failed" >> $GITHUB_STEP_SUMMARY
+
       - name: Lint
         working-directory: svelte_frontends
         run: npm run lint || echo "❌ Lint failed" >> $GITHUB_STEP_SUMMARY
@@ -35,13 +39,13 @@ jobs:
         working-directory: svelte_frontends
         run: npm run check || echo "❌ Type check failed" >> $GITHUB_STEP_SUMMARY
 
-      - name: Build
+      - name: Run unit unit tests
         working-directory: svelte_frontends
-        run: npm run build || echo "❌ Build failed" >> $GITHUB_STEP_SUMMARY
+        run: npm run test:unit || echo "❌ Unit tests failed" >> $GITHUB_STEP_SUMMARY
 
-      - name: Run unit tests
+      - name: Run unit integration tests
         working-directory: svelte_frontends
-        run: npm run test:unit || echo "❌ Tests failed" >> $GITHUB_STEP_SUMMARY
+        run: npm run test:integration || echo "❌ Integration tests failed" >> $GITHUB_STEP_SUMMARY
 
       - name: Report results
         run: |
